/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823"
 * 	found in "iso8650\iso8650.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_ProtocolVersion_H_
#define	_ProtocolVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProtocolVersion {
	ProtocolVersion_version1	= 0
} e_ProtocolVersion;

/* ProtocolVersion */
typedef BIT_STRING_t	 ProtocolVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolVersion;
asn_struct_free_f ProtocolVersion_free;
asn_struct_print_f ProtocolVersion_print;
asn_constr_check_f ProtocolVersion_constraint;
ber_type_decoder_f ProtocolVersion_decode_ber;
der_type_encoder_f ProtocolVersion_encode_der;
xer_type_decoder_f ProtocolVersion_decode_xer;
xer_type_encoder_f ProtocolVersion_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolVersion_H_ */
