/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823"
 * 	found in "iso8650\iso8650.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Requirements_H_
#define	_Requirements_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Requirements {
	Requirements_contextmanagement	= 0,
	Requirements_restoration	= 1
} e_Requirements;

/* Requirements */
typedef BIT_STRING_t	 Requirements_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Requirements;
asn_struct_free_f Requirements_free;
asn_struct_print_f Requirements_print;
asn_constr_check_f Requirements_constraint;
ber_type_decoder_f Requirements_decode_ber;
der_type_encoder_f Requirements_encode_der;
xer_type_decoder_f Requirements_decode_xer;
xer_type_encoder_f Requirements_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Requirements_H_ */
