/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823"
 * 	found in "iso8650\iso8650.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Userdata_H_
#define	_Userdata_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Userdata_PR {
	Userdata_PR_NOTHING,	/* No components present */
	Userdata_PR_simplyencodeddata,
	Userdata_PR_fullyencodeddata
} Userdata_PR;

/* Forward declarations */
struct PDVlist;

/* Userdata */
typedef struct Userdata {
	Userdata_PR present;
	union Userdata_u {
		OCTET_STRING_t	 simplyencodeddata;
		struct fullyencodeddata {
			A_SEQUENCE_OF(struct PDVlist) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} fullyencodeddata;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Userdata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Userdata;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDVlist.h"

#endif	/* _Userdata_H_ */
