/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms-extended-mod3.asn"
 */

#ifndef	_AlternateAccessSelection_H_
#define	_AlternateAccessSelection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"
#include "Unsigned32.h"
#include "IndexRangeSeq.h"
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlternateAccessSelection_PR {
	AlternateAccessSelection_PR_NOTHING,	/* No components present */
	AlternateAccessSelection_PR_selectAccess
} AlternateAccessSelection_PR;
typedef enum selectAccess_PR {
	selectAccess_PR_NOTHING,	/* No components present */
	selectAccess_PR_component,
	selectAccess_PR_index,
	selectAccess_PR_indexRange,
	selectAccess_PR_allElements
} selectAccess_PR;

/* AlternateAccessSelection */
typedef struct AlternateAccessSelection {
	AlternateAccessSelection_PR present;
	union AlternateAccessSelection_u {
		struct selectAccess {
			selectAccess_PR present;
			union AlternateAccessSelection__selectAccess_u {
				Identifier_t	 component;
				Unsigned32_t	 index;
				IndexRangeSeq_t	 indexRange;
				NULL_t	 allElements;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} selectAccess;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlternateAccessSelection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlternateAccessSelection;

#ifdef __cplusplus
}
#endif

#endif	/* _AlternateAccessSelection_H_ */
