/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms-extended-mod3.asn"
 */

#ifndef	_AlternateAccess_H_
#define	_AlternateAccess_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AlternateAccessChoice;

/* AlternateAccess */
typedef struct AlternateAccess {
	A_SEQUENCE_OF(struct AlternateAccessChoice) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlternateAccess_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlternateAccess;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AlternateAccessChoice.h"

#endif	/* _AlternateAccess_H_ */
