/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms-extended-mod3.asn"
 */

#ifndef	_GetNamedVariableListAttributesResponse_H_
#define	_GetNamedVariableListAttributesResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "iso9506/user/listOfVariable.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ListOfVariableSeq;

/* GetNamedVariableListAttributesResponse */
typedef struct GetNamedVariableListAttributesResponse {
	BOOLEAN_t	 mmsDeletable;
	listOfVariable_t listOfVariable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetNamedVariableListAttributesResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetNamedVariableListAttributesResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ListOfVariableSeq.h"

#endif	/* _GetNamedVariableListAttributesResponse_H_ */
