/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms-extended-mod3.asn"
 */

#ifndef	_ObjectClass_H_
#define	_ObjectClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_integer.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectClass_PR {
	ObjectClass_PR_NOTHING,	/* No components present */
	ObjectClass_PR_basicObjectClass
} ObjectClass_PR;
typedef enum basicObjectClass {
	basicObjectClass_namedVariable	= 0,
	basicObjectClass_scatteredAccess	= 1,
	basicObjectClass_namedVariableList	= 2,
	basicObjectClass_namedType	= 3,
	basicObjectClass_semaphore	= 4,
	basicObjectClass_eventCondition	= 5,
	basicObjectClass_eventAction	= 6,
	basicObjectClass_eventEnrollment	= 7,
	basicObjectClass_journal	= 8,
	basicObjectClass_domain	= 9,
	basicObjectClass_programInvocation	= 10,
	basicObjectClass_operatorStation	= 11,
	basicObjectClass_dataExchange	= 12,
	basicObjectClass_accessControlList	= 13
} e_basicObjectClass;

/* ObjectClass */
typedef struct ObjectClass {
	ObjectClass_PR present;
	union ObjectClass_u {
		INTEGER_t	 basicObjectClass;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObjectClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectClass;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectClass_H_ */
