/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms-extended-mod3.asn"
 */

#ifndef	_WriteResponse_H_
#define	_WriteResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "user\WriteResponseList.h"

#ifdef __cplusplus
extern "C" {
#endif


/* WriteResponse */
typedef struct WriteResponse {
	A_SEQUENCE_OF(WriteResponseList_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WriteResponse_t;


/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WriteResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _WriteResponse_H_ */
