/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823"
 * 	found in "iso8650\iso8650.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_ModeSelector_H_
#define	_ModeSelector_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum ModeSelector_PR {
	ModeSelector_PR_modeValue,	/* Member modeValue is present */
} ModeSelector_PR;
typedef enum modeValue {
	modeValue_x4101984mode	= 0,
	modeValue_normalmode	= 1
} e_modeValue;

/* ModeSelector */
typedef struct ModeSelector {
	long	 modeValue;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pModeSelector, ModeSelector_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModeSelector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModeSelector;

#ifdef __cplusplus
}
#endif

#endif	/* _ModeSelector_H_ */
