/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823"
 * 	found in "iso8650\iso8650.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_UserSessionRequirements_H_
#define	_UserSessionRequirements_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UserSessionRequirements {
	UserSessionRequirements_halfduplex	= 0,
	UserSessionRequirements_duplex	= 1,
	UserSessionRequirements_expediteddata	= 2,
	UserSessionRequirements_minorsynchronize	= 3,
	UserSessionRequirements_majorsynchronize	= 4,
	UserSessionRequirements_resynchronize	= 5,
	UserSessionRequirements_activitymanagement	= 6,
	UserSessionRequirements_negotiatedrelease	= 7,
	UserSessionRequirements_capabilitydata	= 8,
	UserSessionRequirements_exceptions	= 9,
	UserSessionRequirements_typeddata	= 10,
	UserSessionRequirements_symmetricsynchronize	= 11,
	UserSessionRequirements_dataseparation	= 12
} e_UserSessionRequirements;

/* UserSessionRequirements */
typedef BIT_STRING_t	 UserSessionRequirements_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserSessionRequirements;
asn_struct_free_f UserSessionRequirements_free;
asn_struct_print_f UserSessionRequirements_print;
asn_constr_check_f UserSessionRequirements_constraint;
ber_type_decoder_f UserSessionRequirements_decode_ber;
der_type_encoder_f UserSessionRequirements_encode_der;
xer_type_decoder_f UserSessionRequirements_decode_xer;
xer_type_encoder_f UserSessionRequirements_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UserSessionRequirements_H_ */
