/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823"
 * 	found in "iso8650\iso8650.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_ContextList_H_
#define	_ContextList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
	long presentationcontextidentifier;
	OBJECT_IDENTIFIER_t	abstractsyntaxname;
	struct transfersyntaxnamelist {
		A_SEQUENCE_OF(OBJECT_IDENTIFIER_t) list;
		asn_struct_ctx_t _asn_ctx;
	} transfersyntaxnamelist;
	
	/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
} ContextListSeq_t;

/* ContextList */
typedef struct ContextList {
	A_SEQUENCE_OF(ContextListSeq_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ContextList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContextList;

#ifdef __cplusplus
}
#endif

#endif	/* _ContextList_H_ */
