/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO8823"
 * 	found in "iso8650\iso8650.asn"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_DefaultContextName_H_
#define	_DefaultContextName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DefaultContextName */
typedef struct DefaultContextName {
	OBJECT_IDENTIFIER_t	 abstractsyntaxname;
	OBJECT_IDENTIFIER_t	 transfersyntaxname;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefaultContextName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefaultContextName;

#ifdef __cplusplus
}
#endif

#endif	/* _DefaultContextName_H_ */
