/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms-extended-mod3.asn"
 */

#ifndef	_AlternateAccessChoice_H_
#define	_AlternateAccessChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlternateAccessSelection.h"
#include "Identifier.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlternateAccessChoice_PR {
	AlternateAccessChoice_PR_NOTHING,	/* No components present */
	AlternateAccessChoice_PR_unnamed,
	AlternateAccessChoice_PR_named
} AlternateAccessChoice_PR;

/* AlternateAccessChoice */
typedef struct AlternateAccessChoice {
	AlternateAccessChoice_PR present;
	union AlternateAccessChoice_u {
		AlternateAccessSelection_t	 unnamed;
		struct named {
			Identifier_t	 componentName;
			AlternateAccessSelection_t	 accesst;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} named;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlternateAccessChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlternateAccessChoice;

#ifdef __cplusplus
}
#endif

#endif	/* _AlternateAccessChoice_H_ */
