/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms-extended-mod3.asn"
 */

#ifndef	_DefineNamedVariableListRequest_H_
#define	_DefineNamedVariableListRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectName.h"
#include "iso9506/user/listOfVariable.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ListOfVariableSeq;

/* DefineNamedVariableListRequest */
typedef struct DefineNamedVariableListRequest {
	ObjectName_t	 variableListName;
	listOfVariable_t listOfVariable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DefineNamedVariableListRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefineNamedVariableListRequest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ListOfVariableSeq.h"

#endif	/* _DefineNamedVariableListRequest_H_ */
