/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "mms-extended-mod3.asn"
 */

#ifndef	_RejectPDU_H_
#define	_RejectPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Unsigned32.h"
#include <NativeInteger.h>
#include <asn_integer.h>
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum rejectReason_PR {
	rejectReason_PR_NOTHING,	/* No components present */
	rejectReason_PR_confirmedRequestPDU,
	rejectReason_PR_confirmedResponsePDU,
	rejectReason_PR_confirmedErrorPDU,
	rejectReason_PR_unconfirmedPDU,
	rejectReason_PR_pduError,
	rejectReason_PR_cancelRequestPDU,
	rejectReason_PR_cancelResponsePDU,
	rejectReason_PR_cancelErrorPDU,
	rejectReason_PR_concludeRequestPDU,
	rejectReason_PR_concludeResponsePDU,
	rejectReason_PR_concludeErrorPDU
} rejectReason_PR;
typedef enum confirmedRequestPDU {
	confirmedRequestPDU_other	= 0,
	confirmedRequestPDU_unrecognizedService	= 1,
	confirmedRequestPDU_unrecognizedModifier	= 2,
	confirmedRequestPDU_invalidInvokeID	= 3,
	confirmedRequestPDU_invalidArgument	= 4,
	confirmedRequestPDU_invalidModifier	= 5,
	confirmedRequestPDU_maxServOutstandingEexceeded	= 6,
	confirmedRequestPDU_maxRecursionExceeded	= 8,
	confirmedRequestPDU_valueOutOfRange	= 9
} e_confirmedRequestPDU;
typedef enum confirmedResponsePDU {
	confirmedResponsePDU_other	= 0,
	confirmedResponsePDU_unrecognizedService	= 1,
	confirmedResponsePDU_invalidInvokeID	= 2,
	confirmedResponsePDU_invalidResult	= 3,
	confirmedResponsePDU_maxRecursionExceeded	= 5,
	confirmedResponsePDU_valueOutOfRange	= 6
} e_confirmedResponsePDU;
typedef enum confirmedErrorPDU {
	confirmedErrorPDU_other	= 0,
	confirmedErrorPDU_unrecognizedService	= 1,
	confirmedErrorPDU_invalidInvokeID	= 2,
	confirmedErrorPDU_invalidServiceError	= 3,
	confirmedErrorPDU_valueOutOfRange	= 4
} e_confirmedErrorPDU;
typedef enum unconfirmedPDU {
	unconfirmedPDU_other	= 0,
	unconfirmedPDU_unrecognizedService	= 1,
	unconfirmedPDU_invalidArgument	= 2,
	unconfirmedPDU_maxRecursionExceeded	= 3,
	unconfirmedPDU_valueOutOfRange	= 4
} e_unconfirmedPDU;
typedef enum pduError {
	pduError_unknownPduType	= 0,
	pduError_invalidPdu	= 1,
	pduError_illegalAcseMapping	= 2
} e_pduError;
typedef enum concludeRequestPDU {
	concludeRequestPDU_other	= 0,
	concludeRequestPDU_invalidArgument	= 1
} e_concludeRequestPDU;
typedef enum concludeResponsePDU {
	concludeResponsePDU_other	= 0,
	concludeResponsePDU_invalidResult	= 1
} e_concludeResponsePDU;
typedef enum concludeErrorPDU {
	concludeErrorPDU_other	= 0,
	concludeErrorPDU_invalidServiceError	= 1,
	concludeErrorPDU_valueOutOfRange	= 2
} e_concludeErrorPDU;

/* RejectPDU */
typedef struct RejectPDU {
	Unsigned32_t	*originalInvokeID	/* OPTIONAL */;
	struct rejectReason {
		rejectReason_PR present;
		union RejectPDU__rejectReason_u {
			long	 confirmedRequestPDU;
			long	 confirmedResponsePDU;
			long	 confirmedErrorPDU;
			long	 unconfirmedPDU;
			INTEGER_t	 pduError;
			NULL_t	 cancelRequestPDU;
			NULL_t	 cancelResponsePDU;
			NULL_t	 cancelErrorPDU;
			long	 concludeRequestPDU;
			long	 concludeResponsePDU;
			long	 concludeErrorPDU;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rejectReason;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RejectPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RejectPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _RejectPDU_H_ */
