/*
 * static_model.h
 *
 * automatically generated from Ver2.ed9.1.scd
 */

#ifndef STATIC_MODEL_H_
#define STATIC_MODEL_H_

#include <stdlib.h>
#include "/libiec61850/api/model.h"

extern IedModel iedModel;
extern LogicalDevice iedModel_UPG;
extern LogicalNode   iedModel_UPG_LLN01;
extern DataObject    iedModel_UPG_LLN01_Beh;
extern DataAttribute iedModel_UPG_LLN01_Beh_q;
extern DataAttribute iedModel_UPG_LLN01_Beh_stVal;
extern DataAttribute iedModel_UPG_LLN01_Beh_t;
extern LogicalNode   iedModel_UPG_LPHD1;
extern DataObject    iedModel_UPG_LPHD1_PhyNam;
extern DataAttribute iedModel_UPG_LPHD1_PhyNam_vendor;
extern DataObject    iedModel_UPG_LPHD1_PhyHealth;
extern DataAttribute iedModel_UPG_LPHD1_PhyHealth_q;
extern DataAttribute iedModel_UPG_LPHD1_PhyHealth_stVal;
extern DataAttribute iedModel_UPG_LPHD1_PhyHealth_t;
extern DataObject    iedModel_UPG_LPHD1_Proxy;
extern DataAttribute iedModel_UPG_LPHD1_Proxy_q;
extern DataAttribute iedModel_UPG_LPHD1_Proxy_stVal;
extern DataAttribute iedModel_UPG_LPHD1_Proxy_t;
extern DataObject    iedModel_UPG_LPHD1_Beh;
extern DataAttribute iedModel_UPG_LPHD1_Beh_q;
extern DataAttribute iedModel_UPG_LPHD1_Beh_stVal;
extern DataAttribute iedModel_UPG_LPHD1_Beh_t;
extern LogicalNode   iedModel_UPG_GGIO0;
extern DataObject    iedModel_UPG_GGIO0_Beh;
extern DataAttribute iedModel_UPG_GGIO0_Beh_q;
extern DataAttribute iedModel_UPG_GGIO0_Beh_stVal;
extern DataAttribute iedModel_UPG_GGIO0_Beh_t;
extern DataObject    iedModel_UPG_GGIO0_ConnStatus;
extern DataAttribute iedModel_UPG_GGIO0_ConnStatus_mag;
extern DataAttribute iedModel_UPG_GGIO0_ConnStatus_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_ConnStatus_q;
extern DataAttribute iedModel_UPG_GGIO0_ConnStatus_t;
extern DataObject    iedModel_UPG_GGIO0_HV;
extern DataAttribute iedModel_UPG_GGIO0_HV_mag;
extern DataAttribute iedModel_UPG_GGIO0_HV_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_HV_q;
extern DataAttribute iedModel_UPG_GGIO0_HV_t;
extern DataObject    iedModel_UPG_GGIO0_LV;
extern DataAttribute iedModel_UPG_GGIO0_LV_mag;
extern DataAttribute iedModel_UPG_GGIO0_LV_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_LV_q;
extern DataAttribute iedModel_UPG_GGIO0_LV_t;
extern DataObject    iedModel_UPG_GGIO0_Pause;
extern DataAttribute iedModel_UPG_GGIO0_Pause_mag;
extern DataAttribute iedModel_UPG_GGIO0_Pause_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_Pause_q;
extern DataAttribute iedModel_UPG_GGIO0_Pause_t;
extern DataObject    iedModel_UPG_GGIO0_Protect1;
extern DataAttribute iedModel_UPG_GGIO0_Protect1_mag;
extern DataAttribute iedModel_UPG_GGIO0_Protect1_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_Protect1_q;
extern DataAttribute iedModel_UPG_GGIO0_Protect1_t;
extern DataObject    iedModel_UPG_GGIO0_Protect2;
extern DataAttribute iedModel_UPG_GGIO0_Protect2_mag;
extern DataAttribute iedModel_UPG_GGIO0_Protect2_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_Protect2_q;
extern DataAttribute iedModel_UPG_GGIO0_Protect2_t;
extern DataObject    iedModel_UPG_GGIO0_Ready;
extern DataAttribute iedModel_UPG_GGIO0_Ready_mag;
extern DataAttribute iedModel_UPG_GGIO0_Ready_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_Ready_q;
extern DataAttribute iedModel_UPG_GGIO0_Ready_t;
extern DataObject    iedModel_UPG_GGIO0_Work;
extern DataAttribute iedModel_UPG_GGIO0_Work_mag;
extern DataAttribute iedModel_UPG_GGIO0_Work_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_Work_q;
extern DataAttribute iedModel_UPG_GGIO0_Work_t;
extern DataObject    iedModel_UPG_GGIO0_Id;
extern DataAttribute iedModel_UPG_GGIO0_Id_mag;
extern DataAttribute iedModel_UPG_GGIO0_Id_mag_f;
extern DataAttribute iedModel_UPG_GGIO0_Id_q;
extern DataAttribute iedModel_UPG_GGIO0_Id_t;
extern DataObject    iedModel_UPG_GGIO0_Rl;
extern DataAttribute iedModel_UPG_GGIO0_Rl_mag;
extern DataAttribute iedModel_UPG_GGIO0_Rl_mag_f;
extern DataAttribute iedModel_UPG_GGIO0_Rl_q;
extern DataAttribute iedModel_UPG_GGIO0_Rl_t;
extern DataObject    iedModel_UPG_GGIO0_Ud;
extern DataAttribute iedModel_UPG_GGIO0_Ud_mag;
extern DataAttribute iedModel_UPG_GGIO0_Ud_mag_f;
extern DataAttribute iedModel_UPG_GGIO0_Ud_q;
extern DataAttribute iedModel_UPG_GGIO0_Ud_t;
extern DataObject    iedModel_UPG_GGIO0_Circ;
extern DataAttribute iedModel_UPG_GGIO0_Circ_mag;
extern DataAttribute iedModel_UPG_GGIO0_Circ_mag_i;
extern DataAttribute iedModel_UPG_GGIO0_Circ_q;
extern DataAttribute iedModel_UPG_GGIO0_Circ_t;
extern DataObject    iedModel_UPG_GGIO0_Iz;
extern DataAttribute iedModel_UPG_GGIO0_Iz_mag;
extern DataAttribute iedModel_UPG_GGIO0_Iz_mag_f;
extern DataAttribute iedModel_UPG_GGIO0_Iz_q;
extern DataAttribute iedModel_UPG_GGIO0_Iz_t;
extern DataObject    iedModel_UPG_GGIO0_Rlz;
extern DataAttribute iedModel_UPG_GGIO0_Rlz_mag;
extern DataAttribute iedModel_UPG_GGIO0_Rlz_mag_f;
extern DataAttribute iedModel_UPG_GGIO0_Rlz_q;
extern DataAttribute iedModel_UPG_GGIO0_Rlz_t;
extern LogicalNode   iedModel_UPG_GGIO1;
extern DataObject    iedModel_UPG_GGIO1_Beh;
extern DataAttribute iedModel_UPG_GGIO1_Beh_q;
extern DataAttribute iedModel_UPG_GGIO1_Beh_stVal;
extern DataAttribute iedModel_UPG_GGIO1_Beh_t;
extern DataObject    iedModel_UPG_GGIO1_Id;
extern DataAttribute iedModel_UPG_GGIO1_Id_mag;
extern DataAttribute iedModel_UPG_GGIO1_Id_mag_f;
extern DataAttribute iedModel_UPG_GGIO1_Id_q;
extern DataAttribute iedModel_UPG_GGIO1_Id_t;
extern DataObject    iedModel_UPG_GGIO1_Ud;
extern DataAttribute iedModel_UPG_GGIO1_Ud_mag;
extern DataAttribute iedModel_UPG_GGIO1_Ud_mag_f;
extern DataAttribute iedModel_UPG_GGIO1_Ud_q;
extern DataAttribute iedModel_UPG_GGIO1_Ud_t;
extern DataObject    iedModel_UPG_GGIO1_Iz;
extern DataAttribute iedModel_UPG_GGIO1_Iz_mag;
extern DataAttribute iedModel_UPG_GGIO1_Iz_mag_f;
extern DataAttribute iedModel_UPG_GGIO1_Iz_q;
extern DataAttribute iedModel_UPG_GGIO1_Iz_t;
extern DataObject    iedModel_UPG_GGIO1_PKZ;
extern DataAttribute iedModel_UPG_GGIO1_PKZ_mag;
extern DataAttribute iedModel_UPG_GGIO1_PKZ_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_PKZ_q;
extern DataAttribute iedModel_UPG_GGIO1_PKZ_t;
extern DataObject    iedModel_UPG_GGIO1_POS;
extern DataAttribute iedModel_UPG_GGIO1_POS_mag;
extern DataAttribute iedModel_UPG_GGIO1_POS_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_POS_q;
extern DataAttribute iedModel_UPG_GGIO1_POS_t;
extern DataObject    iedModel_UPG_GGIO1_SMU;
extern DataAttribute iedModel_UPG_GGIO1_SMU_mag;
extern DataAttribute iedModel_UPG_GGIO1_SMU_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_SMU_q;
extern DataAttribute iedModel_UPG_GGIO1_SMU_t;
extern DataObject    iedModel_UPG_GGIO1_TAminus;
extern DataAttribute iedModel_UPG_GGIO1_TAminus_mag;
extern DataAttribute iedModel_UPG_GGIO1_TAminus_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_TAminus_q;
extern DataAttribute iedModel_UPG_GGIO1_TAminus_t;
extern DataObject    iedModel_UPG_GGIO1_TAplus;
extern DataAttribute iedModel_UPG_GGIO1_TAplus_mag;
extern DataAttribute iedModel_UPG_GGIO1_TAplus_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_TAplus_q;
extern DataAttribute iedModel_UPG_GGIO1_TAplus_t;
extern DataObject    iedModel_UPG_GGIO1_TBminus;
extern DataAttribute iedModel_UPG_GGIO1_TBminus_mag;
extern DataAttribute iedModel_UPG_GGIO1_TBminus_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_TBminus_q;
extern DataAttribute iedModel_UPG_GGIO1_TBminus_t;
extern DataObject    iedModel_UPG_GGIO1_TBplus;
extern DataAttribute iedModel_UPG_GGIO1_TBplus_mag;
extern DataAttribute iedModel_UPG_GGIO1_TBplus_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_TBplus_q;
extern DataAttribute iedModel_UPG_GGIO1_TBplus_t;
extern DataObject    iedModel_UPG_GGIO1_TCminus;
extern DataAttribute iedModel_UPG_GGIO1_TCminus_mag;
extern DataAttribute iedModel_UPG_GGIO1_TCminus_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_TCminus_q;
extern DataAttribute iedModel_UPG_GGIO1_TCminus_t;
extern DataObject    iedModel_UPG_GGIO1_TCplus;
extern DataAttribute iedModel_UPG_GGIO1_TCplus_mag;
extern DataAttribute iedModel_UPG_GGIO1_TCplus_mag_i;
extern DataAttribute iedModel_UPG_GGIO1_TCplus_q;
extern DataAttribute iedModel_UPG_GGIO1_TCplus_t;



#define IEDMODEL_UPG (&iedModel_UPG)
#define IEDMODEL_UPG_LLN01 (&iedModel_UPG_LLN01)
#define IEDMODEL_UPG_LLN01_Beh (&iedModel_UPG_LLN01_Beh)
#define IEDMODEL_UPG_LLN01_Beh_q (&iedModel_UPG_LLN01_Beh_q)
#define IEDMODEL_UPG_LLN01_Beh_stVal (&iedModel_UPG_LLN01_Beh_stVal)
#define IEDMODEL_UPG_LLN01_Beh_t (&iedModel_UPG_LLN01_Beh_t)
#define IEDMODEL_UPG_LPHD1 (&iedModel_UPG_LPHD1)
#define IEDMODEL_UPG_LPHD1_PhyNam (&iedModel_UPG_LPHD1_PhyNam)
#define IEDMODEL_UPG_LPHD1_PhyNam_vendor (&iedModel_UPG_LPHD1_PhyNam_vendor)
#define IEDMODEL_UPG_LPHD1_PhyHealth (&iedModel_UPG_LPHD1_PhyHealth)
#define IEDMODEL_UPG_LPHD1_PhyHealth_q (&iedModel_UPG_LPHD1_PhyHealth_q)
#define IEDMODEL_UPG_LPHD1_PhyHealth_stVal (&iedModel_UPG_LPHD1_PhyHealth_stVal)
#define IEDMODEL_UPG_LPHD1_PhyHealth_t (&iedModel_UPG_LPHD1_PhyHealth_t)
#define IEDMODEL_UPG_LPHD1_Proxy (&iedModel_UPG_LPHD1_Proxy)
#define IEDMODEL_UPG_LPHD1_Proxy_q (&iedModel_UPG_LPHD1_Proxy_q)
#define IEDMODEL_UPG_LPHD1_Proxy_stVal (&iedModel_UPG_LPHD1_Proxy_stVal)
#define IEDMODEL_UPG_LPHD1_Proxy_t (&iedModel_UPG_LPHD1_Proxy_t)
#define IEDMODEL_UPG_LPHD1_Beh (&iedModel_UPG_LPHD1_Beh)
#define IEDMODEL_UPG_LPHD1_Beh_q (&iedModel_UPG_LPHD1_Beh_q)
#define IEDMODEL_UPG_LPHD1_Beh_stVal (&iedModel_UPG_LPHD1_Beh_stVal)
#define IEDMODEL_UPG_LPHD1_Beh_t (&iedModel_UPG_LPHD1_Beh_t)
#define IEDMODEL_UPG_GGIO0 (&iedModel_UPG_GGIO0)
#define IEDMODEL_UPG_GGIO0_Beh (&iedModel_UPG_GGIO0_Beh)
#define IEDMODEL_UPG_GGIO0_Beh_q (&iedModel_UPG_GGIO0_Beh_q)
#define IEDMODEL_UPG_GGIO0_Beh_stVal (&iedModel_UPG_GGIO0_Beh_stVal)
#define IEDMODEL_UPG_GGIO0_Beh_t (&iedModel_UPG_GGIO0_Beh_t)
#define IEDMODEL_UPG_GGIO0_ConnStatus (&iedModel_UPG_GGIO0_ConnStatus)
#define IEDMODEL_UPG_GGIO0_ConnStatus_mag (&iedModel_UPG_GGIO0_ConnStatus_mag)
#define IEDMODEL_UPG_GGIO0_ConnStatus_mag_i (&iedModel_UPG_GGIO0_ConnStatus_mag_i)
#define IEDMODEL_UPG_GGIO0_ConnStatus_q (&iedModel_UPG_GGIO0_ConnStatus_q)
#define IEDMODEL_UPG_GGIO0_ConnStatus_t (&iedModel_UPG_GGIO0_ConnStatus_t)
#define IEDMODEL_UPG_GGIO0_HV (&iedModel_UPG_GGIO0_HV)
#define IEDMODEL_UPG_GGIO0_HV_mag (&iedModel_UPG_GGIO0_HV_mag)
#define IEDMODEL_UPG_GGIO0_HV_mag_i (&iedModel_UPG_GGIO0_HV_mag_i)
#define IEDMODEL_UPG_GGIO0_HV_q (&iedModel_UPG_GGIO0_HV_q)
#define IEDMODEL_UPG_GGIO0_HV_t (&iedModel_UPG_GGIO0_HV_t)
#define IEDMODEL_UPG_GGIO0_LV (&iedModel_UPG_GGIO0_LV)
#define IEDMODEL_UPG_GGIO0_LV_mag (&iedModel_UPG_GGIO0_LV_mag)
#define IEDMODEL_UPG_GGIO0_LV_mag_i (&iedModel_UPG_GGIO0_LV_mag_i)
#define IEDMODEL_UPG_GGIO0_LV_q (&iedModel_UPG_GGIO0_LV_q)
#define IEDMODEL_UPG_GGIO0_LV_t (&iedModel_UPG_GGIO0_LV_t)
#define IEDMODEL_UPG_GGIO0_Pause (&iedModel_UPG_GGIO0_Pause)
#define IEDMODEL_UPG_GGIO0_Pause_mag (&iedModel_UPG_GGIO0_Pause_mag)
#define IEDMODEL_UPG_GGIO0_Pause_mag_i (&iedModel_UPG_GGIO0_Pause_mag_i)
#define IEDMODEL_UPG_GGIO0_Pause_q (&iedModel_UPG_GGIO0_Pause_q)
#define IEDMODEL_UPG_GGIO0_Pause_t (&iedModel_UPG_GGIO0_Pause_t)
#define IEDMODEL_UPG_GGIO0_Protect1 (&iedModel_UPG_GGIO0_Protect1)
#define IEDMODEL_UPG_GGIO0_Protect1_mag (&iedModel_UPG_GGIO0_Protect1_mag)
#define IEDMODEL_UPG_GGIO0_Protect1_mag_i (&iedModel_UPG_GGIO0_Protect1_mag_i)
#define IEDMODEL_UPG_GGIO0_Protect1_q (&iedModel_UPG_GGIO0_Protect1_q)
#define IEDMODEL_UPG_GGIO0_Protect1_t (&iedModel_UPG_GGIO0_Protect1_t)
#define IEDMODEL_UPG_GGIO0_Protect2 (&iedModel_UPG_GGIO0_Protect2)
#define IEDMODEL_UPG_GGIO0_Protect2_mag (&iedModel_UPG_GGIO0_Protect2_mag)
#define IEDMODEL_UPG_GGIO0_Protect2_mag_i (&iedModel_UPG_GGIO0_Protect2_mag_i)
#define IEDMODEL_UPG_GGIO0_Protect2_q (&iedModel_UPG_GGIO0_Protect2_q)
#define IEDMODEL_UPG_GGIO0_Protect2_t (&iedModel_UPG_GGIO0_Protect2_t)
#define IEDMODEL_UPG_GGIO0_Ready (&iedModel_UPG_GGIO0_Ready)
#define IEDMODEL_UPG_GGIO0_Ready_mag (&iedModel_UPG_GGIO0_Ready_mag)
#define IEDMODEL_UPG_GGIO0_Ready_mag_i (&iedModel_UPG_GGIO0_Ready_mag_i)
#define IEDMODEL_UPG_GGIO0_Ready_q (&iedModel_UPG_GGIO0_Ready_q)
#define IEDMODEL_UPG_GGIO0_Ready_t (&iedModel_UPG_GGIO0_Ready_t)
#define IEDMODEL_UPG_GGIO0_Work (&iedModel_UPG_GGIO0_Work)
#define IEDMODEL_UPG_GGIO0_Work_mag (&iedModel_UPG_GGIO0_Work_mag)
#define IEDMODEL_UPG_GGIO0_Work_mag_i (&iedModel_UPG_GGIO0_Work_mag_i)
#define IEDMODEL_UPG_GGIO0_Work_q (&iedModel_UPG_GGIO0_Work_q)
#define IEDMODEL_UPG_GGIO0_Work_t (&iedModel_UPG_GGIO0_Work_t)
#define IEDMODEL_UPG_GGIO0_Id (&iedModel_UPG_GGIO0_Id)
#define IEDMODEL_UPG_GGIO0_Id_mag (&iedModel_UPG_GGIO0_Id_mag)
#define IEDMODEL_UPG_GGIO0_Id_mag_f (&iedModel_UPG_GGIO0_Id_mag_f)
#define IEDMODEL_UPG_GGIO0_Id_q (&iedModel_UPG_GGIO0_Id_q)
#define IEDMODEL_UPG_GGIO0_Id_t (&iedModel_UPG_GGIO0_Id_t)
#define IEDMODEL_UPG_GGIO0_Rl (&iedModel_UPG_GGIO0_Rl)
#define IEDMODEL_UPG_GGIO0_Rl_mag (&iedModel_UPG_GGIO0_Rl_mag)
#define IEDMODEL_UPG_GGIO0_Rl_mag_f (&iedModel_UPG_GGIO0_Rl_mag_f)
#define IEDMODEL_UPG_GGIO0_Rl_q (&iedModel_UPG_GGIO0_Rl_q)
#define IEDMODEL_UPG_GGIO0_Rl_t (&iedModel_UPG_GGIO0_Rl_t)
#define IEDMODEL_UPG_GGIO0_Ud (&iedModel_UPG_GGIO0_Ud)
#define IEDMODEL_UPG_GGIO0_Ud_mag (&iedModel_UPG_GGIO0_Ud_mag)
#define IEDMODEL_UPG_GGIO0_Ud_mag_f (&iedModel_UPG_GGIO0_Ud_mag_f)
#define IEDMODEL_UPG_GGIO0_Ud_q (&iedModel_UPG_GGIO0_Ud_q)
#define IEDMODEL_UPG_GGIO0_Ud_t (&iedModel_UPG_GGIO0_Ud_t)
#define IEDMODEL_UPG_GGIO0_Circ (&iedModel_UPG_GGIO0_Circ)
#define IEDMODEL_UPG_GGIO0_Circ_mag (&iedModel_UPG_GGIO0_Circ_mag)
#define IEDMODEL_UPG_GGIO0_Circ_mag_i (&iedModel_UPG_GGIO0_Circ_mag_i)
#define IEDMODEL_UPG_GGIO0_Circ_q (&iedModel_UPG_GGIO0_Circ_q)
#define IEDMODEL_UPG_GGIO0_Circ_t (&iedModel_UPG_GGIO0_Circ_t)
#define IEDMODEL_UPG_GGIO0_Iz (&iedModel_UPG_GGIO0_Iz)
#define IEDMODEL_UPG_GGIO0_Iz_mag (&iedModel_UPG_GGIO0_Iz_mag)
#define IEDMODEL_UPG_GGIO0_Iz_mag_f (&iedModel_UPG_GGIO0_Iz_mag_f)
#define IEDMODEL_UPG_GGIO0_Iz_q (&iedModel_UPG_GGIO0_Iz_q)
#define IEDMODEL_UPG_GGIO0_Iz_t (&iedModel_UPG_GGIO0_Iz_t)
#define IEDMODEL_UPG_GGIO0_Rlz (&iedModel_UPG_GGIO0_Rlz)
#define IEDMODEL_UPG_GGIO0_Rlz_mag (&iedModel_UPG_GGIO0_Rlz_mag)
#define IEDMODEL_UPG_GGIO0_Rlz_mag_f (&iedModel_UPG_GGIO0_Rlz_mag_f)
#define IEDMODEL_UPG_GGIO0_Rlz_q (&iedModel_UPG_GGIO0_Rlz_q)
#define IEDMODEL_UPG_GGIO0_Rlz_t (&iedModel_UPG_GGIO0_Rlz_t)
#define IEDMODEL_UPG_GGIO1 (&iedModel_UPG_GGIO1)
#define IEDMODEL_UPG_GGIO1_Beh (&iedModel_UPG_GGIO1_Beh)
#define IEDMODEL_UPG_GGIO1_Beh_q (&iedModel_UPG_GGIO1_Beh_q)
#define IEDMODEL_UPG_GGIO1_Beh_stVal (&iedModel_UPG_GGIO1_Beh_stVal)
#define IEDMODEL_UPG_GGIO1_Beh_t (&iedModel_UPG_GGIO1_Beh_t)
#define IEDMODEL_UPG_GGIO1_Id (&iedModel_UPG_GGIO1_Id)
#define IEDMODEL_UPG_GGIO1_Id_mag (&iedModel_UPG_GGIO1_Id_mag)
#define IEDMODEL_UPG_GGIO1_Id_mag_f (&iedModel_UPG_GGIO1_Id_mag_f)
#define IEDMODEL_UPG_GGIO1_Id_q (&iedModel_UPG_GGIO1_Id_q)
#define IEDMODEL_UPG_GGIO1_Id_t (&iedModel_UPG_GGIO1_Id_t)
#define IEDMODEL_UPG_GGIO1_Ud (&iedModel_UPG_GGIO1_Ud)
#define IEDMODEL_UPG_GGIO1_Ud_mag (&iedModel_UPG_GGIO1_Ud_mag)
#define IEDMODEL_UPG_GGIO1_Ud_mag_f (&iedModel_UPG_GGIO1_Ud_mag_f)
#define IEDMODEL_UPG_GGIO1_Ud_q (&iedModel_UPG_GGIO1_Ud_q)
#define IEDMODEL_UPG_GGIO1_Ud_t (&iedModel_UPG_GGIO1_Ud_t)
#define IEDMODEL_UPG_GGIO1_Iz (&iedModel_UPG_GGIO1_Iz)
#define IEDMODEL_UPG_GGIO1_Iz_mag (&iedModel_UPG_GGIO1_Iz_mag)
#define IEDMODEL_UPG_GGIO1_Iz_mag_f (&iedModel_UPG_GGIO1_Iz_mag_f)
#define IEDMODEL_UPG_GGIO1_Iz_q (&iedModel_UPG_GGIO1_Iz_q)
#define IEDMODEL_UPG_GGIO1_Iz_t (&iedModel_UPG_GGIO1_Iz_t)
#define IEDMODEL_UPG_GGIO1_PKZ (&iedModel_UPG_GGIO1_PKZ)
#define IEDMODEL_UPG_GGIO1_PKZ_mag (&iedModel_UPG_GGIO1_PKZ_mag)
#define IEDMODEL_UPG_GGIO1_PKZ_mag_i (&iedModel_UPG_GGIO1_PKZ_mag_i)
#define IEDMODEL_UPG_GGIO1_PKZ_q (&iedModel_UPG_GGIO1_PKZ_q)
#define IEDMODEL_UPG_GGIO1_PKZ_t (&iedModel_UPG_GGIO1_PKZ_t)
#define IEDMODEL_UPG_GGIO1_POS (&iedModel_UPG_GGIO1_POS)
#define IEDMODEL_UPG_GGIO1_POS_mag (&iedModel_UPG_GGIO1_POS_mag)
#define IEDMODEL_UPG_GGIO1_POS_mag_i (&iedModel_UPG_GGIO1_POS_mag_i)
#define IEDMODEL_UPG_GGIO1_POS_q (&iedModel_UPG_GGIO1_POS_q)
#define IEDMODEL_UPG_GGIO1_POS_t (&iedModel_UPG_GGIO1_POS_t)
#define IEDMODEL_UPG_GGIO1_SMU (&iedModel_UPG_GGIO1_SMU)
#define IEDMODEL_UPG_GGIO1_SMU_mag (&iedModel_UPG_GGIO1_SMU_mag)
#define IEDMODEL_UPG_GGIO1_SMU_mag_i (&iedModel_UPG_GGIO1_SMU_mag_i)
#define IEDMODEL_UPG_GGIO1_SMU_q (&iedModel_UPG_GGIO1_SMU_q)
#define IEDMODEL_UPG_GGIO1_SMU_t (&iedModel_UPG_GGIO1_SMU_t)
#define IEDMODEL_UPG_GGIO1_TAminus (&iedModel_UPG_GGIO1_TAminus)
#define IEDMODEL_UPG_GGIO1_TAminus_mag (&iedModel_UPG_GGIO1_TAminus_mag)
#define IEDMODEL_UPG_GGIO1_TAminus_mag_i (&iedModel_UPG_GGIO1_TAminus_mag_i)
#define IEDMODEL_UPG_GGIO1_TAminus_q (&iedModel_UPG_GGIO1_TAminus_q)
#define IEDMODEL_UPG_GGIO1_TAminus_t (&iedModel_UPG_GGIO1_TAminus_t)
#define IEDMODEL_UPG_GGIO1_TAplus (&iedModel_UPG_GGIO1_TAplus)
#define IEDMODEL_UPG_GGIO1_TAplus_mag (&iedModel_UPG_GGIO1_TAplus_mag)
#define IEDMODEL_UPG_GGIO1_TAplus_mag_i (&iedModel_UPG_GGIO1_TAplus_mag_i)
#define IEDMODEL_UPG_GGIO1_TAplus_q (&iedModel_UPG_GGIO1_TAplus_q)
#define IEDMODEL_UPG_GGIO1_TAplus_t (&iedModel_UPG_GGIO1_TAplus_t)
#define IEDMODEL_UPG_GGIO1_TBminus (&iedModel_UPG_GGIO1_TBminus)
#define IEDMODEL_UPG_GGIO1_TBminus_mag (&iedModel_UPG_GGIO1_TBminus_mag)
#define IEDMODEL_UPG_GGIO1_TBminus_mag_i (&iedModel_UPG_GGIO1_TBminus_mag_i)
#define IEDMODEL_UPG_GGIO1_TBminus_q (&iedModel_UPG_GGIO1_TBminus_q)
#define IEDMODEL_UPG_GGIO1_TBminus_t (&iedModel_UPG_GGIO1_TBminus_t)
#define IEDMODEL_UPG_GGIO1_TBplus (&iedModel_UPG_GGIO1_TBplus)
#define IEDMODEL_UPG_GGIO1_TBplus_mag (&iedModel_UPG_GGIO1_TBplus_mag)
#define IEDMODEL_UPG_GGIO1_TBplus_mag_i (&iedModel_UPG_GGIO1_TBplus_mag_i)
#define IEDMODEL_UPG_GGIO1_TBplus_q (&iedModel_UPG_GGIO1_TBplus_q)
#define IEDMODEL_UPG_GGIO1_TBplus_t (&iedModel_UPG_GGIO1_TBplus_t)
#define IEDMODEL_UPG_GGIO1_TCminus (&iedModel_UPG_GGIO1_TCminus)
#define IEDMODEL_UPG_GGIO1_TCminus_mag (&iedModel_UPG_GGIO1_TCminus_mag)
#define IEDMODEL_UPG_GGIO1_TCminus_mag_i (&iedModel_UPG_GGIO1_TCminus_mag_i)
#define IEDMODEL_UPG_GGIO1_TCminus_q (&iedModel_UPG_GGIO1_TCminus_q)
#define IEDMODEL_UPG_GGIO1_TCminus_t (&iedModel_UPG_GGIO1_TCminus_t)
#define IEDMODEL_UPG_GGIO1_TCplus (&iedModel_UPG_GGIO1_TCplus)
#define IEDMODEL_UPG_GGIO1_TCplus_mag (&iedModel_UPG_GGIO1_TCplus_mag)
#define IEDMODEL_UPG_GGIO1_TCplus_mag_i (&iedModel_UPG_GGIO1_TCplus_mag_i)
#define IEDMODEL_UPG_GGIO1_TCplus_q (&iedModel_UPG_GGIO1_TCplus_q)
#define IEDMODEL_UPG_GGIO1_TCplus_t (&iedModel_UPG_GGIO1_TCplus_t)

#endif /* STATIC_MODEL_H_ */

